# Generated by Django 4.1.7 on 2023-03-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_rename_cat_barber_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
